language: python

python:
    - '3.6'

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10

env:
    - DJANGO_SETTINGS_MODULE="pur_beurre_v2.settings.travis"
    global:
      - PGPORT=5433

services:
    - postgresql

before_script:
    - pip install -r requirement.txt



script:
    - python manage.py test

branches:
    only:
        - staging

