language: python
python:
    - '3.6'

branches:
    only:
        - staging
        - password

before_script:
    - pip install -r requirements.txt

services:
    - postgresql

addons:
  postgresql: "9.6"

env:
    - DJANGO_SETTINGS_MODULE="pur_beurre_v2.settings.travis"

script:
    - python manage.py test


