language: python

python:
    - '3.6.6'

addons:
  postgresql: "10.5"

services:
    - postgresql

before_script:
    - pip install -r requirement.txt

env:
    - DJANGO_SETTINGS_MODULE="pur_beurre_v2.settings.travis"

script:
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py test

branches:
    only:
        - staging

