language: python
python:
    - '3.6.6'

before_script:
    - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="pur_beurre_v2.settings"

services:
    - postgresql

script:
    - ./manage.py test

branches:
    only:
        - staging

