language: python
python:
    - '3.6.6'

services:
    - postgresql

before_script:
    - pip install -r requirement.txt
    - psql -c 'create database travis_ci_test;' -U postgres

env:
    - DJANGO_SETTINGS_MODULE="pur_beurre_v2.settings.travis"

script:
    - python manage.py makemigrations
    - python manage.py migrate
    - python manage.py test

branches:
    only:
        - staging

