language: python
python:
    - '3.6.6'

env: DJANGO_SETTINGS_MODULE=pur_beurre_v2.settings.travis

services:
    - postgresql

before_script:
    - pip install -r requirement.txt
    - psql -c 'create database travis_ci_test;' -U postgres

script:
    - ./manage.py makemigrations
    - ./manage.py migrate
    - ./manage.py test

branches:
    only:
        - staging

